name = "drizzle-demo"
compatibility_flags = ["nodejs_compat"]
compatibility_date = "2024-09-23"

[build]
command = "pnpm run build"
output_directory = ".next"

[site]
bucket = ".next"

[env.production]
vars = { ENVIRONMENT = "production" }

[env.development]
vars = { ENVIRONMENT = "development" }
