name = "drizzle-demo"
compatibility_date = "2025-01-24"

[build]
command = "pnpm run build"
output_directory = ".next"

[site]
bucket = ".next"

[env.production]
vars = { ENVIRONMENT = "production" }

[env.development]
vars = { ENVIRONMENT = "development" }
